#!/usr/bin/env bash
# Regenerates schema.sql: upstream Belimbing's own Laravel migrations run on
# an empty PostgreSQL database, dumped schema-only.
#
#   PGHOST=localhost PGPORT=5433 PGUSER=postgres PGPASSWORD=... \
#     ./regenerate.sh <belimbing-commit>
#
# Needs git, php (with pdo_pgsql), composer, createdb/dropdb and pg_dump, and
# a PostgreSQL role that may create databases. The commit becomes the fixture
# header and must equal `Bilimbi.Core.Compatibility.compatibility_source/0`;
# the fixture test fails when the two disagree. The scratch database and the
# checkout live under a temporary directory and are removed on exit.
#
# Only the public upstream repository is ever dumped. A customer database, or
# a fork carrying customer modules, is never a fixture source.
set -euo pipefail

commit="${1:?usage: regenerate.sh <belimbing-commit>}"
repository="${BELIMBING_REPOSITORY:-https://github.com/BelimbingApp/belimbing.git}"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
scratch="$(mktemp -d)"
database="bilimbi_fixture_$(date +%s)"

cleanup() {
  dropdb --if-exists --force "$database" >/dev/null 2>&1 || true
  rm -rf "$scratch"
}
trap cleanup EXIT

git clone --quiet "$repository" "$scratch/belimbing"
git -C "$scratch/belimbing" checkout --quiet "$commit"
resolved="$(git -C "$scratch/belimbing" rev-parse HEAD)"

(
  cd "$scratch/belimbing"
  composer install --no-dev --no-interaction --no-progress --prefer-dist --quiet
  cp .env.example .env
  php artisan key:generate --force --no-interaction >/dev/null
)

createdb "$database"

# Laravel reads the connection from the environment; the two operator values
# are placeholders the migrations insist on, and the dump carries no rows.
(
  cd "$scratch/belimbing"
  env DB_CONNECTION=pgsql DB_URL= \
    DB_HOST="${PGHOST:-localhost}" DB_PORT="${PGPORT:-5432}" \
    DB_DATABASE="$database" DB_USERNAME="${PGUSER:-postgres}" \
    DB_PASSWORD="${PGPASSWORD:-}" \
    CACHE_STORE=array SESSION_DRIVER=array QUEUE_CONNECTION=sync \
    PLATFORM_OPERATOR_COMPANY_NAME="Platform Operator" \
    PLATFORM_OPERATOR_COMPANY_CODE="platform_operator" \
    php artisan migrate --force --no-interaction >/dev/null
)

{
  printf -- '--\n'
  printf -- '-- Schema-only dump of upstream Belimbing, the compatibility reference.\n'
  printf -- '-- belimbing-commit: %s\n' "$resolved"
  printf -- "-- Generated by regenerate.sh: that commit's own Laravel migrations on an\n"
  printf -- '-- empty PostgreSQL 18 database, then pg_dump --schema-only. No rows, no\n'
  printf -- '-- owners, no psql meta-commands. Do not edit by hand.\n'
  printf -- '--\n\n'
  # pg_dump 17.6+ brackets the file in \restrict ... \unrestrict, which only
  # psql understands; the test loads the file over the wire.
  pg_dump --schema-only --no-owner --no-privileges --no-tablespaces \
    --no-security-labels "$database" |
    grep -v '^\\restrict \|^\\unrestrict '
} >"$here/schema.sql"

echo "wrote $here/schema.sql from $repository at $resolved"
