defmodule Bilimbi.Core.User.TestFixtures do
  @moduledoc """
  Lightweight User fixtures for public-API tests.

  These temporary tables exercise query behavior. Exact PostgreSQL
  compatibility is covered independently by the schema contract.

  Company and Employee table DDL is not restated here: it is defined once by
  the module that owns it and reused through that module's fixtures.
  """

  alias Bilimbi.Base.Database.TestTables
  alias Bilimbi.Base.Repo
  alias Bilimbi.Core.Employee.TestFixtures, as: EmployeeFixtures
  alias Bilimbi.Core.User.Password
  alias Ecto.Adapters.SQL

  def password_hash(password \\ "password"), do: Password.hash(password)

  def legacy_password_hash(password \\ "password") do
    password
    |> Bcrypt.hash_pwd_salt(log_rounds: 4)
    |> String.replace_prefix("$2b$", "$2y$")
  end

  # Generated by PHP's PASSWORD_ARGON2ID with Belimbing's canonical
  # memory=19456 KiB, time=2, threads=1 configuration.
  def laravel_argon2_password_hash do
    "$argon2id$v=19$m=19456,t=2,p=1$" <>
      "OTk4dW1zRzBTUFkyQlE5ZA$5feI+G5D3AYm7qIywmS4kZKR4T8gyfzWTIG5JWALvtk"
  end

  alias Bilimbi.Base.Authz.ContributionValidator
  alias Bilimbi.Base.ModuleRegistry.ContributionRegistry

  def create_user_tables! do
    apply(EmployeeFixtures, :create_employee_tables!, [])
    apply(Bilimbi.Core.Company.TestFixtures, :create_external_access_tables!, [])

    create_users_table!()

    SQL.query!(
      Repo,
      """
      CREATE TEMPORARY TABLE password_reset_tokens (
        email varchar(255) PRIMARY KEY,
        token varchar(255) NOT NULL,
        created_at timestamp(0) without time zone
      ) ON COMMIT PRESERVE ROWS
      """,
      []
    )

    create_notifications_table!()
  end

  def create_users_table!(opts \\ []) do
    persistent = TestTables.persistent?(opts)

    SQL.query!(
      Repo,
      """
      #{TestTables.create(persistent)} users (
        id bigserial PRIMARY KEY,
        company_id bigint,
        employee_id bigint,
        name varchar(255) NOT NULL,
        email varchar(255) NOT NULL,
        email_verified_at timestamp(0) without time zone,
        password varchar(255) NOT NULL,
        remember_token varchar(100),
        created_at timestamp(0) without time zone,
        updated_at timestamp(0) without time zone
      ) #{TestTables.on_commit(persistent)}
      """,
      []
    )

    # Named explicitly, not an inline UNIQUE. PostgreSQL would name that
    # `users_email_key`, but the migration creates `users_email_unique` and the
    # changeset maps that name to a field error. A fixture that invents its own
    # constraint name turns a caught error into a raised ConstraintError.
    SQL.query!(Repo, "CREATE UNIQUE INDEX users_email_unique ON users (email)", [])
  end

  def create_bootstrap_receipt_table!(opts \\ []) do
    persistent = TestTables.persistent?(opts)

    SQL.query!(
      Repo,
      """
      #{TestTables.create(persistent)} bilimbi_user_bootstrap (
        id bigint PRIMARY KEY,
        tenant_name varchar(255) NOT NULL,
        company_name varchar(255) NOT NULL,
        company_code varchar(255) NOT NULL,
        admin_email varchar(255) NOT NULL,
        user_id bigint NOT NULL,
        company_id bigint NOT NULL,
        tenant_id bigint NOT NULL,
        completed_at timestamp(0) without time zone NOT NULL,
        CONSTRAINT bilimbi_user_bootstrap_singleton CHECK (id = 1)
      ) #{TestTables.on_commit(persistent)}
      """,
      []
    )
  end

  def create_user_database_queries_table! do
    SQL.query!(
      Repo,
      """
      CREATE TEMPORARY TABLE user_database_queries (
        id bigserial PRIMARY KEY,
        user_id bigint NOT NULL,
        name varchar(150) NOT NULL,
        slug varchar(200) NOT NULL,
        prompt text,
        sql_query text NOT NULL,
        description text,
        icon varchar(100),
        created_at timestamp(0) without time zone,
        updated_at timestamp(0) without time zone
      ) ON COMMIT PRESERVE ROWS
      """,
      []
    )

    SQL.query!(
      Repo,
      "CREATE UNIQUE INDEX user_database_queries_user_id_slug_unique ON user_database_queries (user_id, slug)",
      []
    )

    SQL.query!(
      Repo,
      "CREATE INDEX user_database_queries_user_id_index ON user_database_queries (user_id)",
      []
    )
  end

  def install_user_authz_registry! do
    ContributionRegistry.put_consumers_for_test!(
      %{settings: [], authz: user_authz_snapshot(), menu: []},
      "user-test"
    )
  end

  @doc """
  The validated Authz snapshot of Base Authz, Core Company's directory and
  Core User's own capabilities. A test that signs a user in and reads a
  company through `Bilimbi.Core.Company` needs it installed: Company's
  summary withholds its sensitive fields through the reader's effective
  capabilities, which the company directory resolves.
  """
  def user_authz_snapshot do
    ContributionValidator.validate_contributions!([
      %{
        descriptor: %{
          id: "base/authz",
          otp_app: :bilimbi_base_authz
        },
        payload: Bilimbi.Base.Authz.Contributions.contributions()[:authz]
      },
      %{
        descriptor: %{
          id: "core/company",
          otp_app: :bilimbi_core_company
        },
        payload: %{
          domains: %{"core" => "Core platform modules"},
          capabilities: [
            "admin.company.view",
            "admin.company.list",
            "admin.company.manage"
          ],
          roles: %{},
          company_directory: Bilimbi.Core.Company.AuthzCompanyDirectory
        }
      },
      %{
        descriptor: %{
          id: "core/user",
          otp_app: :bilimbi_core_user
        },
        payload: Bilimbi.Core.User.Contributions.contributions()[:authz]
      }
    ])
  end

  def insert_user!(attributes \\ %{}) do
    attributes =
      Map.merge(
        %{
          id: 91,
          company_id: 73,
          employee_id: nil,
          name: "Ada Lovelace",
          email: "ada@example.com",
          email_verified_at: nil,
          password_hash: password_hash(),
          remember_token: nil
        },
        attributes
      )

    SQL.query!(
      Repo,
      """
      INSERT INTO users (
        id, company_id, employee_id, name, email, email_verified_at, password, remember_token
      )
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
      """,
      [
        attributes.id,
        attributes.company_id,
        attributes.employee_id,
        attributes.name,
        attributes.email,
        attributes.email_verified_at,
        attributes.password_hash,
        attributes.remember_token
      ]
    )
  end

  def stored_password(user_id) do
    %{rows: [[password]]} =
      SQL.query!(Repo, "SELECT password FROM users WHERE id = $1", [user_id])

    password
  end

  def stored_remember_token(user_id) do
    %{rows: [[remember_token]]} =
      SQL.query!(Repo, "SELECT remember_token FROM users WHERE id = $1", [user_id])

    remember_token
  end

  def stored_reset_token(email) do
    %{rows: [[token]]} =
      SQL.query!(Repo, "SELECT token FROM password_reset_tokens WHERE email = $1", [email])

    token
  end

  def expire_reset_token!(email) do
    SQL.query!(
      Repo,
      "UPDATE password_reset_tokens SET created_at = $1 WHERE email = $2",
      [~N[2000-01-01 00:00:00], email]
    )
  end

  def create_user_pins_table! do
    SQL.query!(
      Repo,
      """
      CREATE TEMPORARY TABLE IF NOT EXISTS user_pins (
        id bigserial PRIMARY KEY,
        user_id bigint NOT NULL,
        label varchar(150) NOT NULL,
        url varchar(500) NOT NULL,
        url_hash char(32) NOT NULL,
        icon varchar(100),
        sort_order smallint NOT NULL DEFAULT 0,
        created_at timestamp(0) without time zone,
        updated_at timestamp(0) without time zone
      ) ON COMMIT PRESERVE ROWS
      """,
      []
    )

    SQL.query!(
      Repo,
      "CREATE UNIQUE INDEX IF NOT EXISTS user_pins_user_id_url_hash_unique ON user_pins (user_id, url_hash)",
      []
    )

    SQL.query!(
      Repo,
      "CREATE INDEX IF NOT EXISTS user_pins_user_id_sort_order_index ON user_pins (user_id, sort_order)",
      []
    )
  end

  def create_notifications_table! do
    SQL.query!(
      Repo,
      """
      CREATE TEMPORARY TABLE IF NOT EXISTS notifications (
        id uuid PRIMARY KEY,
        type varchar(255) NOT NULL,
        notifiable_type varchar(255) NOT NULL,
        notifiable_id bigint NOT NULL,
        data text NOT NULL,
        read_at timestamp(0) without time zone,
        created_at timestamp(0) without time zone,
        updated_at timestamp(0) without time zone
      ) ON COMMIT PRESERVE ROWS
      """,
      []
    )

    SQL.query!(
      Repo,
      "CREATE INDEX IF NOT EXISTS notifications_notifiable_type_notifiable_id_index ON notifications (notifiable_type, notifiable_id)",
      []
    )
  end
end
