defmodule Bilimbi.Core.User.TestFixtures do
  @moduledoc """
  Lightweight User fixtures for public-API tests.

  These temporary tables exercise query behavior. Exact PostgreSQL
  compatibility is covered independently by the schema contract.

  Company and Employee table DDL is not restated here: it is defined once by
  the module that owns it and reused through that module's fixtures.
  """

  alias Bilimbi.Base.Repo
  alias Bilimbi.Core.Employee.TestFixtures, as: EmployeeFixtures
  alias Bilimbi.Core.User.Password
  alias Ecto.Adapters.SQL

  def password_hash(password \\ "password"), do: Password.hash(password)

  def legacy_password_hash(password \\ "password") do
    password
    |> Bcrypt.hash_pwd_salt(log_rounds: 4)
    |> String.replace_prefix("$2b$", "$2y$")
  end

  # Generated by PHP's PASSWORD_ARGON2ID with Belimbing's canonical
  # memory=19456 KiB, time=2, threads=1 configuration.
  def laravel_argon2_password_hash do
    "$argon2id$v=19$m=19456,t=2,p=1$" <>
      "OTk4dW1zRzBTUFkyQlE5ZA$5feI+G5D3AYm7qIywmS4kZKR4T8gyfzWTIG5JWALvtk"
  end

  alias Bilimbi.Base.Authz.ContributionValidator
  alias Bilimbi.Base.ModuleRegistry.ContributionRegistry
  alias Bilimbi.Base.Tenancy.Identity
  alias Bilimbi.Base.Tenancy.Scope

  def create_user_tables! do
    apply(EmployeeFixtures, :create_employee_tables!, [])

    SQL.query!(
      Repo,
      """
      CREATE TEMPORARY TABLE users (
        id bigserial PRIMARY KEY,
        company_id bigint,
        employee_id bigint,
        name varchar(255) NOT NULL,
        email varchar(255) NOT NULL,
        email_verified_at timestamp(0) without time zone,
        password varchar(255) NOT NULL,
        remember_token varchar(100),
        created_at timestamp(0) without time zone,
        updated_at timestamp(0) without time zone
      ) ON COMMIT PRESERVE ROWS
      """,
      []
    )

    # Named explicitly, not an inline UNIQUE. PostgreSQL would name that
    # `users_email_key`, but the migration creates `users_email_unique` and the
    # changeset maps that name to a field error. A fixture that invents its own
    # constraint name turns a caught error into a raised ConstraintError.
    SQL.query!(Repo, "CREATE UNIQUE INDEX users_email_unique ON users (email)", [])

    SQL.query!(
      Repo,
      """
      CREATE TEMPORARY TABLE password_reset_tokens (
        email varchar(255) PRIMARY KEY,
        token varchar(255) NOT NULL,
        created_at timestamp(0) without time zone
      ) ON COMMIT PRESERVE ROWS
      """,
      []
    )

    create_notifications_table!()
  end

  def create_sessions_table! do
    SQL.query!(
      Repo,
      """
      CREATE TEMPORARY TABLE sessions (
        id varchar(255) PRIMARY KEY,
        user_id bigint,
        ip_address varchar(45),
        user_agent text,
        payload text NOT NULL,
        last_activity integer NOT NULL
      ) ON COMMIT PRESERVE ROWS
      """,
      []
    )

    SQL.query!(Repo, "CREATE INDEX sessions_user_id_index ON sessions (user_id)", [])

    SQL.query!(
      Repo,
      "CREATE INDEX sessions_last_activity_index ON sessions (last_activity)",
      []
    )
  end

  def create_user_database_queries_table! do
    SQL.query!(
      Repo,
      """
      CREATE TEMPORARY TABLE user_database_queries (
        id bigserial PRIMARY KEY,
        user_id bigint NOT NULL,
        name varchar(150) NOT NULL,
        slug varchar(200) NOT NULL,
        prompt text,
        sql_query text NOT NULL,
        description text,
        icon varchar(100),
        created_at timestamp(0) without time zone,
        updated_at timestamp(0) without time zone
      ) ON COMMIT PRESERVE ROWS
      """,
      []
    )

    SQL.query!(
      Repo,
      "CREATE UNIQUE INDEX user_database_queries_user_id_slug_unique ON user_database_queries (user_id, slug)",
      []
    )

    SQL.query!(
      Repo,
      "CREATE INDEX user_database_queries_user_id_index ON user_database_queries (user_id)",
      []
    )
  end

  def install_user_authz_registry! do
    authz =
      ContributionValidator.validate_contributions!([
        %{
          descriptor: %{
            id: "base/authz",
            otp_app: :bilimbi_base_authz
          },
          payload: Bilimbi.Base.Authz.Contributions.contributions()[:authz]
        },
        %{
          descriptor: %{
            id: "core/company",
            otp_app: :bilimbi_core_company
          },
          payload: %{
            domains: %{"core" => "Core platform modules"},
            capabilities: [
              "admin.company.view",
              "admin.company.list",
              "admin.company.manage"
            ],
            roles: %{},
            company_directory: Bilimbi.Core.Company.AuthzCompanyDirectory
          }
        },
        %{
          descriptor: %{
            id: "core/user",
            otp_app: :bilimbi_core_user
          },
          payload: Bilimbi.Core.User.Contributions.contributions()[:authz]
        }
      ])

    ContributionRegistry.put_snapshot_for_test!(%{
      graph_fingerprint: "user-test",
      consumers: %{settings: [], authz: authz, menu: []}
    })
  end

  def operator_scope(tenant_id \\ 1) do
    Scope.for_tenant(%Identity{
      id: tenant_id,
      name: "Operator Tenant",
      status: "active",
      is_platform_operator: true
    })
  end

  def tenant_scope(tenant_id \\ 2) do
    Scope.for_tenant(%Identity{
      id: tenant_id,
      name: "Tenant #{tenant_id}",
      status: "active",
      is_platform_operator: false
    })
  end

  def grant_role!(company_id, user_id, role_code, grant_all \\ false) do
    now = NaiveDateTime.utc_now() |> NaiveDateTime.truncate(:second)

    %{rows: [[role_id]]} =
      SQL.query!(
        Repo,
        """
        INSERT INTO base_authz_roles (company_id, name, code, is_system, grant_all, created_at, updated_at)
        VALUES ($1, $2, $3, false, $4, $5, $6)
        ON CONFLICT (company_id, code) DO UPDATE SET grant_all = EXCLUDED.grant_all
        RETURNING id
        """,
        [company_id, role_code, role_code, grant_all, now, now]
      )

    SQL.query!(
      Repo,
      """
      INSERT INTO base_authz_principal_roles (company_id, principal_type, principal_id, role_id, created_at, updated_at)
      VALUES ($1, 'user', $2, $3, $4, $5)
      ON CONFLICT (company_id, principal_type, principal_id, role_id) DO NOTHING
      """,
      [company_id, user_id, role_id, now, now]
    )

    role_id
  end

  def grant_capability!(company_id, user_id, capability_key, is_allowed \\ true) do
    now = NaiveDateTime.utc_now() |> NaiveDateTime.truncate(:second)

    SQL.query!(
      Repo,
      """
      INSERT INTO base_authz_principal_capabilities (
        company_id, principal_type, principal_id, capability_key, is_allowed, created_at, updated_at
      )
      VALUES ($1, 'user', $2, $3, $4, $5, $6)
      ON CONFLICT (company_id, principal_type, principal_id, capability_key)
      DO UPDATE SET is_allowed = EXCLUDED.is_allowed
      """,
      [company_id, user_id, capability_key, is_allowed, now, now]
    )
  end

  def insert_user!(attributes \\ %{}) do
    attributes =
      Map.merge(
        %{
          id: 91,
          company_id: 73,
          employee_id: nil,
          name: "Ada Lovelace",
          email: "ada@example.com",
          email_verified_at: nil,
          password_hash: password_hash(),
          remember_token: nil
        },
        attributes
      )

    SQL.query!(
      Repo,
      """
      INSERT INTO users (
        id, company_id, employee_id, name, email, email_verified_at, password, remember_token
      )
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
      """,
      [
        attributes.id,
        attributes.company_id,
        attributes.employee_id,
        attributes.name,
        attributes.email,
        attributes.email_verified_at,
        attributes.password_hash,
        attributes.remember_token
      ]
    )
  end

  def stored_password(user_id) do
    %{rows: [[password]]} =
      SQL.query!(Repo, "SELECT password FROM users WHERE id = $1", [user_id])

    password
  end

  def stored_remember_token(user_id) do
    %{rows: [[remember_token]]} =
      SQL.query!(Repo, "SELECT remember_token FROM users WHERE id = $1", [user_id])

    remember_token
  end

  def stored_reset_token(email) do
    %{rows: [[token]]} =
      SQL.query!(Repo, "SELECT token FROM password_reset_tokens WHERE email = $1", [email])

    token
  end

  def expire_reset_token!(email) do
    SQL.query!(
      Repo,
      "UPDATE password_reset_tokens SET created_at = $1 WHERE email = $2",
      [~N[2000-01-01 00:00:00], email]
    )
  end

  def create_user_pins_table! do
    SQL.query!(
      Repo,
      """
      CREATE TEMPORARY TABLE user_pins (
        id bigserial PRIMARY KEY,
        user_id bigint NOT NULL,
        label varchar(150) NOT NULL,
        url varchar(500) NOT NULL,
        url_hash char(32) NOT NULL,
        icon varchar(100),
        sort_order smallint NOT NULL DEFAULT 0,
        created_at timestamp(0) without time zone,
        updated_at timestamp(0) without time zone
      ) ON COMMIT PRESERVE ROWS
      """,
      []
    )

    SQL.query!(
      Repo,
      "CREATE UNIQUE INDEX user_pins_user_id_url_hash_unique ON user_pins (user_id, url_hash)",
      []
    )

    SQL.query!(
      Repo,
      "CREATE INDEX user_pins_user_id_sort_order_index ON user_pins (user_id, sort_order)",
      []
    )
  end

  def create_notifications_table! do
    SQL.query!(
      Repo,
      """
      CREATE TEMPORARY TABLE IF NOT EXISTS notifications (
        id uuid PRIMARY KEY,
        type varchar(255) NOT NULL,
        notifiable_type varchar(255) NOT NULL,
        notifiable_id bigint NOT NULL,
        data text NOT NULL,
        read_at timestamp(0) without time zone,
        created_at timestamp(0) without time zone,
        updated_at timestamp(0) without time zone
      ) ON COMMIT PRESERVE ROWS
      """,
      []
    )

    SQL.query!(
      Repo,
      "CREATE INDEX IF NOT EXISTS notifications_notifiable_type_notifiable_id_index ON notifications (notifiable_type, notifiable_id)",
      []
    )
  end
end
