defmodule Bilimbi.Core.User.TestFixtures do
  @moduledoc """
  Lightweight User fixtures for public-API tests.

  These temporary tables exercise query behavior. Exact PostgreSQL
  compatibility is covered independently by the schema contract.

  Company and Employee table DDL is not restated here: it is defined once by
  the module that owns it and reused through that module's fixtures.
  """

  alias Bilimbi.Base.Repo
  alias Bilimbi.Core.Employee.TestFixtures, as: EmployeeFixtures
  alias Bilimbi.Core.User.Password
  alias Ecto.Adapters.SQL

  def password_hash(password \\ "password"), do: Password.hash(password)

  def legacy_password_hash(password \\ "password") do
    password
    |> Bcrypt.hash_pwd_salt(log_rounds: 4)
    |> String.replace_prefix("$2b$", "$2y$")
  end

  # Generated by PHP's PASSWORD_ARGON2ID with Belimbing's canonical
  # memory=19456 KiB, time=2, threads=1 configuration.
  def laravel_argon2_password_hash do
    "$argon2id$v=19$m=19456,t=2,p=1$" <>
      "OTk4dW1zRzBTUFkyQlE5ZA$5feI+G5D3AYm7qIywmS4kZKR4T8gyfzWTIG5JWALvtk"
  end

  def create_user_tables! do
    apply(EmployeeFixtures, :create_employee_tables!, [])

    SQL.query!(
      Repo,
      """
      CREATE TEMPORARY TABLE users (
        id bigserial PRIMARY KEY,
        company_id bigint,
        employee_id bigint,
        name varchar(255) NOT NULL,
        email varchar(255) NOT NULL,
        email_verified_at timestamp(0) without time zone,
        password varchar(255) NOT NULL,
        remember_token varchar(100),
        created_at timestamp(0) without time zone,
        updated_at timestamp(0) without time zone
      ) ON COMMIT PRESERVE ROWS
      """,
      []
    )

    # Named explicitly, not an inline UNIQUE. PostgreSQL would name that
    # `users_email_key`, but the migration creates `users_email_unique` and the
    # changeset maps that name to a field error. A fixture that invents its own
    # constraint name turns a caught error into a raised ConstraintError.
    SQL.query!(Repo, "CREATE UNIQUE INDEX users_email_unique ON users (email)", [])

    SQL.query!(
      Repo,
      """
      CREATE TEMPORARY TABLE password_reset_tokens (
        email varchar(255) PRIMARY KEY,
        token varchar(255) NOT NULL,
        created_at timestamp(0) without time zone
      ) ON COMMIT PRESERVE ROWS
      """,
      []
    )
  end

  def insert_user!(attributes \\ %{}) do
    attributes =
      Map.merge(
        %{
          id: 91,
          company_id: 73,
          employee_id: nil,
          name: "Ada Lovelace",
          email: "ada@example.com",
          email_verified_at: nil,
          password_hash: password_hash(),
          remember_token: nil
        },
        attributes
      )

    SQL.query!(
      Repo,
      """
      INSERT INTO users (
        id, company_id, employee_id, name, email, email_verified_at, password, remember_token
      )
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
      """,
      [
        attributes.id,
        attributes.company_id,
        attributes.employee_id,
        attributes.name,
        attributes.email,
        attributes.email_verified_at,
        attributes.password_hash,
        attributes.remember_token
      ]
    )
  end

  def stored_password(user_id) do
    %{rows: [[password]]} =
      SQL.query!(Repo, "SELECT password FROM users WHERE id = $1", [user_id])

    password
  end

  def stored_remember_token(user_id) do
    %{rows: [[remember_token]]} =
      SQL.query!(Repo, "SELECT remember_token FROM users WHERE id = $1", [user_id])

    remember_token
  end

  def stored_reset_token(email) do
    %{rows: [[token]]} =
      SQL.query!(Repo, "SELECT token FROM password_reset_tokens WHERE email = $1", [email])

    token
  end

  def expire_reset_token!(email) do
    SQL.query!(
      Repo,
      "UPDATE password_reset_tokens SET created_at = $1 WHERE email = $2",
      [~N[2000-01-01 00:00:00], email]
    )
  end
end
