defmodule Mix.Tasks.Bilimbi.Tenant.Provision do
  @shortdoc "Provisions a customer tenant and its primary company"

  @moduledoc """
  Atomically provisions a tenant and its first primary company.

      mix bilimbi.tenant.provision --tenant-name "Acme tenant" --company-name "Acme Sdn. Bhd." --company-code "acme"

  All options are required. Tenant and company IDs are generated by PostgreSQL;
  this task never accepts or assigns semantic numeric IDs.
  """

  use Mix.Task

  alias Bilimbi.Core.Company

  @switches [tenant_name: :string, company_name: :string, company_code: :string]

  @impl Mix.Task
  def run(arguments) do
    {options, positional, invalid} = OptionParser.parse(arguments, strict: @switches)

    if positional != [] or invalid != [] do
      Mix.raise("invalid arguments; run mix help bilimbi.tenant.provision")
    end

    tenant_name = required_option!(options, :tenant_name)
    company_name = required_option!(options, :company_name)
    company_code = required_option!(options, :company_code)

    Mix.Task.run("app.start")

    case Company.provision_tenant(
           %{name: tenant_name},
           %{name: company_name, code: company_code}
         ) do
      {:ok, result} ->
        Mix.shell().info(
          "Tenant ready: tenant #{result.tenant.id}, primary company #{result.company.id}."
        )

      {:error, %Ecto.Changeset{} = changeset} ->
        Mix.raise("tenant provisioning failed: #{inspect(changeset.errors)}")
    end
  end

  defp required_option!(options, key) do
    case Keyword.get(options, key) do
      value when is_binary(value) ->
        case String.trim(value) do
          "" -> missing_option!(key)
          normalized -> normalized
        end

      _other ->
        missing_option!(key)
    end
  end

  defp missing_option!(key) do
    option = key |> Atom.to_string() |> String.replace("_", "-")
    Mix.raise("--#{option} is required")
  end
end
