defmodule BilimbiWeb.ModuleHooks do
  @moduledoc """
  Build-time hook composition for the validated workspace.

  Read compiled HEEx macro-component metadata, never glob phoenix-colocated:
  that directory can retain files belonging to unmounted applications. Import
  extracted hook files directly so duplicate names within a Phoenix manifest
  cannot be silently overwritten before we check them.

  This adapter uses LiveView 1.2.9's ColocatedAssets.Entry metadata contract.
  Recheck it and the extraction path when upgrading LiveView. The hook name is
  Phoenix's declaring-module namespace plus the local dot-prefixed name; no
  second naming registry or runtime script installation is involved.
  """

  alias Bilimbi.Base.ModuleRegistry.MixDiscovery

  def write!(workspace_root, build_path) do
    owners =
      Enum.map(MixDiscovery.discover_workspace!(workspace_root), fn descriptor ->
        %{id: descriptor.id, otp_app: descriptor.otp_app, namespace: descriptor.namespace}
      end) ++ [%{id: "web", otp_app: :web, namespace: BilimbiWeb}]

    entries = Enum.flat_map(owners, &entries!(&1, build_path))
    validate_names!(entries)

    imports =
      entries
      |> Enum.with_index()
      |> Enum.map_join("\n", fn {entry, index} ->
        "import hook#{index} from #{js_string(entry.import)};"
      end)

    values =
      entries
      |> Enum.with_index()
      |> Enum.map_join(",\n", fn {entry, index} ->
        "  [#{js_string(entry.name)}]: hook#{index}"
      end)

    content =
      "// Generated by compile.bilimbi_hooks; do not edit.\n#{imports}\nexport const hooks = {\n#{values}\n};\n"

    path = Path.join(build_path, "bilimbi-hooks/index.js")

    if File.regular?(path) and File.read!(path) == content do
      {:noop, []}
    else
      File.mkdir_p!(Path.dirname(path))
      File.write!(path, content)
      {:ok, []}
    end
  end

  defp entries!(owner, build_path) do
    app_file =
      Path.join([build_path, "lib", to_string(owner.otp_app), "ebin", "#{owner.otp_app}.app"])

    modules =
      case :file.consult(String.to_charlist(app_file)) do
        {:ok, [{:application, app, properties}]} when app == owner.otp_app ->
          Keyword.fetch!(properties, :modules)

        other ->
          Mix.raise(
            "Cannot collect hooks for #{owner.id}: compile its application first (#{inspect(other)})"
          )
      end

    modules
    |> Enum.sort()
    |> Enum.flat_map(fn module ->
      unless Code.ensure_loaded?(module),
        do: Mix.raise("Cannot load hook owner #{inspect(module)}")

      for {_component, entries} <- Phoenix.Component.MacroComponent.get_data(module),
          %{
            callback: Phoenix.LiveView.ColocatedJS,
            data: %{key: "hooks", name: name},
            filename: filename
          } <- entries do
        prefix = inspect(owner.namespace) <> "."

        unless String.starts_with?(name, prefix) do
          Mix.raise("Hook #{name} from #{owner.id} must use its descriptor namespace #{prefix}")
        end

        import = "phoenix-colocated/#{owner.otp_app}/#{inspect(module)}/#{filename}"
        file = Path.join(build_path, import)

        unless File.regular?(file),
          do: Mix.raise("Missing extracted hook #{name}: #{file}; recompile its owner")

        %{name: name, owner: owner.id, import: import}
      end
    end)
  end

  defp validate_names!(entries) do
    entries
    |> Enum.group_by(& &1.name)
    |> Enum.each(fn
      {_name, [_entry]} ->
        :ok

      {name, clashes} ->
        owners = Enum.map_join(clashes, ", ", &"#{&1.owner} (#{&1.import})")
        Mix.raise("Colocated hook name clash: #{name} contributed by #{owners}")
    end)
  end

  # JSON string escaping without another build-tool dependency.
  defp js_string(value), do: IO.iodata_to_binary([?", Phoenix.HTML.javascript_escape(value), ?"])
end

defmodule Mix.Tasks.Compile.BilimbiHooks do
  @moduledoc false
  use Mix.Task.Compiler

  @recursive true

  @impl true
  def run(_arguments) do
    workspace_root = Mix.Project.config() |> Keyword.fetch!(:bilimbi_workspace_root)
    BilimbiWeb.ModuleHooks.write!(workspace_root, Mix.Project.build_path())
  end
end
