[
  id: "core/compatibility",
  kind: :module,
  layer: :core,
  required: true,
  otp_app: :bilimbi_core_compatibility,
  namespace: Bilimbi.Core.Compatibility,
  dependencies: [
    "base/dashboard",
    "base/database",
    "base/locale",
    "base/menu",
    "base/queue",
    "base/schedule",
    "base/ui",
    "base/module_registry",
    "base/principal_directory",
    "base/authz",
    "base/session",
    "base/settings",
    "base/system",
    "base/tenancy",
    "base/audit",
    "core/company",
    "core/geonames",
    "core/address",
    "core/employee",
    "core/user"
  ],
  migrations: nil,
  web: nil,
  schema_contract: nil,
  contribution_provider: nil
]
