defmodule Bilimbi.Base.Workflow.ProcessDefinitionTest do
  use ExUnit.Case, async: true

  alias Bilimbi.Base.Workflow.{
    ContributionValidator,
    TestFixtures,
    TestProcessAdapter,
    TestProcessContributions
  }

  # Golden digests generated by Belimbing's ProcessDefinition::fingerprint,
  # ProcessStep and DependencyMode at d53a790f75b36a052362bb5f7b5c361c8ac72983.
  # These are generic owner fixtures; CI needs no PHP or private owner source.
  @golden [
    "a4187aada29acf70279c3a7ca4499b6e5b8a760b457348122a997f3323dcb51c",
    "bb97118b5111f737e3a1b7cbc5e2117a19eb84df9f5b554cf76988160343677a",
    "5377ea6df4a99fc3742452363ec2fbe63248d43f59c4217e99bf83f51a131442",
    "122fc4e74f1bc8b89335ee8a007db7b73fd7122abbf3d84b49b4a58a841eec2a",
    "d753380f0863b283ec416f50d2f40a10a2f4a4bd1ab8eef247e62b8c5e852661",
    "6a5f714d36b7f09ff5766a994efe439da709d2f266caf051c254d0885d8215d5",
    "d8734c952aa99f3063990f6c66d72469bd76e2a502df59e1a2fa0aeecddd7a49"
  ]

  test "all seven parallel subsets preserve legacy PHP v1 fingerprints" do
    import Bitwise
    base = TestProcessContributions.parallel()

    for {expected, mask} <- Enum.with_index(@golden, 1) do
      steps =
        base.steps
        |> Enum.with_index()
        |> Enum.filter(fn {_step, index} -> band(mask, bsl(1, index)) != 0 end)
        |> Enum.map(&elem(&1, 0))

      key = "example.parallel." <> Enum.map_join(steps, "-", & &1.key)
      assert validate(%{base | key: key, steps: steps}).fingerprint == expected
    end
  end

  test "legacy unicode, slashes, line separators, sorted objects and empty lists match PHP" do
    definition = %{
      key: "example.codec",
      version: 1,
      subject: "example.record",
      adapter: TestProcessAdapter,
      steps: [
        %{
          key: "encode",
          label: "Unicode / ü",
          executor_key: "example.encode",
          input: %{"z" => %{"empty" => [], "nested" => %{"z" => true, "a" => false}}, "a" => nil},
          metadata: %{"text" => "line\u2028break\u2029/ ü"}
        }
      ]
    }

    assert validate(definition).fingerprint ==
             "1bd20fb5c29721d527fc704bc98de79fcdd378a9a453f51b3cb90f43da46fcd6"

    [step] = definition.steps

    other = %{
      definition
      | steps: [
          %{
            step
            | input: %{
                "z" => %{"empty" => %{}, "nested" => %{"z" => true, "a" => false}},
                "a" => nil
              }
          }
        ]
    }

    refute validate(definition).fingerprint == validate(other).fingerprint
  end

  test "process graph, provenance and duplicate contracts fail before execution" do
    base = TestProcessContributions.parallel()
    [first | rest] = base.steps

    for bad <- [
          %{base | version: 0},
          %{base | subject: "missing.subject"},
          %{base | adapter: TestProcessContributions},
          %{base | steps: [first, first]},
          %{base | steps: [Map.put(first, :dependencies, [%{step_key: "absent"}]) | rest]},
          %{base | steps: [Map.put(first, :dependencies, [%{step_key: first.key}]) | rest]},
          %{base | steps: [Map.put(first, :dependency_mode, "none") | rest]}
        ],
        do: assert_raise(ArgumentError, fn -> validate(bad) end)

    cycle = %{
      base
      | steps: [
          Map.put(first, :dependencies, [%{step_key: "second"}]),
          %{key: "second", label: "Second", dependencies: [%{step_key: "first"}]}
        ]
    }

    assert_raise ArgumentError, ~r/cycle/, fn -> validate(cycle) end
    assert_raise ArgumentError, ~r/duplicate processes/, fn -> registry([base, base]) end
  end

  test "unsupported legacy float and numeric-key serialization refuses explicitly" do
    base = TestProcessContributions.parallel()
    [first | rest] = base.steps
    float = %{base | steps: [%{first | input: %{"weight" => 1.0}} | rest]}
    assert_raise ArgumentError, ~r/cannot fingerprint floats/, fn -> validate(float) end
    numeric = %{base | steps: [%{first | input: %{"10" => "ten", "2" => "two"}} | rest]}
    assert_raise ArgumentError, ~r/numeric object keys/, fn -> validate(numeric) end

    assert_raise ArgumentError, ~r/unknown process fields/, fn ->
      validate(Map.put(base, :fingerprint_format, :legacy_v1))
    end
  end

  defp validate(definition),
    do: registry([definition]).processes[{definition.key, definition.version}]

  defp registry(definitions) do
    entry = TestFixtures.entry()

    ContributionValidator.validate_contributions!([
      %{entry | payload: Map.put(entry.payload, :processes, definitions)}
    ])
  end
end
