defmodule BilimbiWeb.RouteOverlap do
  @moduledoc false

  # Phoenix's compiled route table includes direct host routes, injected routes,
  # and routes generated by helpers such as live_dashboard. A manifest-only
  # check misses direct declarations and can silently shadow a mounted route.
  # Routes are checked in match order: one owner may place a strictly more
  # specific route before a general one, and every other overlap fails.
  def __after_compile__(env, _bytecode) do
    validate_routes!(env.module.__routes__())
  end

  def validate_routes!(routes) do
    routes = Enum.map(routes, &{&1, segments(&1)})

    routes
    |> Enum.with_index()
    |> Enum.each(fn {{left, left_segments}, index} ->
      routes
      |> Enum.drop(index + 1)
      |> Enum.each(fn {right, right_segments} ->
        if verb_overlap?(left.verb, right.verb) and
             overlap?(left_segments, right_segments) and
             not (owner(left) == owner(right) and
                    strictly_more_specific?(left_segments, right_segments)) do
          raise ArgumentError,
                "route overlap: #{describe(left)} conflicts with #{describe(right)}"
        end
      end)
    end)

    :ok
  end

  defp owner(route), do: Map.get(route.metadata, :bilimbi_route_owner, {:web, "web/router"})

  defp describe(route) do
    {layer, source} = owner(route)
    "#{layer}/#{source} #{route.verb} #{route.path}"
  end

  defp verb_overlap?(left, right), do: left == right or left == :* or right == :*

  defp segments(route) do
    path =
      if Map.get(route, :kind) == :forward,
        do: route.path <> "/*_forward_path_info",
        else: route.path

    path |> String.split("/", trim: true) |> Enum.map(&segment/1)
  end

  defp segment(segment) do
    case :binary.match(segment, [":", "*"]) do
      :nomatch ->
        {:literal, segment}

      {at, 1} ->
        case binary_part(segment, at, byte_size(segment) - at) do
          "*" <> _ -> {:glob, binary_part(segment, 0, at)}
          ":" <> name -> {:param, binary_part(segment, 0, at), suffix(name)}
        end
    end
  end

  defp suffix(name) do
    case Regex.run(~r/^\w+(.*)$/, name) do
      [_, suffix] -> suffix
      nil -> ""
    end
  end

  defp overlap?([], []), do: true
  defp overlap?([{:glob, ""}], _), do: true
  defp overlap?(_, [{:glob, ""}]), do: true
  defp overlap?([{:glob, prefix}], [other | _]), do: compatible?({:param, prefix, ""}, other)
  defp overlap?([other | _], [{:glob, prefix}]), do: compatible?(other, {:param, prefix, ""})
  defp overlap?([], _), do: false
  defp overlap?(_, []), do: false

  defp overlap?([left | left_rest], [right | right_rest]),
    do: compatible?(left, right) and overlap?(left_rest, right_rest)

  defp compatible?({:glob, prefix}, other), do: compatible?({:param, prefix, ""}, other)
  defp compatible?(other, {:glob, prefix}), do: compatible?(other, {:param, prefix, ""})
  defp compatible?({:literal, left}, {:literal, right}), do: left == right

  defp compatible?({:literal, literal}, {:param, prefix, suffix}),
    do: literal_matches?(literal, prefix, suffix)

  defp compatible?({:param, prefix, suffix}, {:literal, literal}),
    do: literal_matches?(literal, prefix, suffix)

  defp compatible?({:param, left_prefix, left_suffix}, {:param, right_prefix, right_suffix}) do
    (String.starts_with?(left_prefix, right_prefix) or
       String.starts_with?(right_prefix, left_prefix)) and
      (String.ends_with?(left_suffix, right_suffix) or
         String.ends_with?(right_suffix, left_suffix))
  end

  defp literal_matches?(literal, prefix, suffix) do
    String.starts_with?(literal, prefix) and String.ends_with?(literal, suffix) and
      byte_size(literal) >= byte_size(prefix) + byte_size(suffix)
  end

  defp strictly_more_specific?(specific, general),
    do: covers?(general, specific) and not covers?(specific, general)

  defp covers?([], []), do: true
  defp covers?([{:glob, ""}], _), do: true
  defp covers?([{:glob, prefix}], [{:glob, other}]), do: String.starts_with?(other, prefix)
  defp covers?([{:glob, prefix}], [other | _]), do: covers_segment?({:param, prefix, ""}, other)

  defp covers?([general | general_rest], [specific | specific_rest]),
    do: covers_segment?(general, specific) and covers?(general_rest, specific_rest)

  defp covers?(_, _), do: false

  defp covers_segment?({:literal, general}, {:literal, specific}), do: general == specific

  defp covers_segment?({:param, prefix, suffix}, {:literal, literal}),
    do: literal_matches?(literal, prefix, suffix)

  defp covers_segment?({:param, prefix, suffix}, {:param, other_prefix, other_suffix}),
    do: String.starts_with?(other_prefix, prefix) and String.ends_with?(other_suffix, suffix)

  defp covers_segment?(_, _), do: false
end
