defmodule BilimbiWeb.RouteOverlap do
  @moduledoc false

  # Phoenix's compiled route table includes direct host routes, injected routes,
  # and routes generated by helpers such as live_dashboard. A manifest-only
  # check misses direct declarations and can silently shadow a mounted route.
  def __after_compile__(env, bytecode) do
    {:module, router} = :code.load_binary(env.module, ~c"nofile", bytecode)
    validate_routes!(router.__routes__())
  end

  def validate_routes!(routes) do
    routes
    |> Enum.with_index()
    |> Enum.each(fn {left, index} ->
      routes
      |> Enum.drop(index + 1)
      |> Enum.each(fn right ->
        if verb_overlap?(left.verb, right.verb) and
             path_overlap?(left.path, right.path) and
             (owner(left) != owner(right) or left.path == right.path) do
          raise ArgumentError,
                "route overlap: #{describe(left)} conflicts with #{describe(right)}"
        end
      end)
    end)

    :ok
  end

  defp owner(route), do: Map.get(route.metadata, :bilimbi_route_owner, {:web, "web/router"})

  defp describe(route) do
    {layer, source} = owner(route)
    "#{layer}/#{source} #{route.verb} #{route.path}"
  end

  defp verb_overlap?(left, right), do: left == right or left == :* or right == :*

  defp path_overlap?(left, right) do
    segments_overlap?(String.split(left, "/", trim: true), String.split(right, "/", trim: true))
  end

  defp segments_overlap?([], []), do: true
  defp segments_overlap?(["*" <> _], _), do: true
  defp segments_overlap?(_, ["*" <> _]), do: true
  defp segments_overlap?([], _), do: false
  defp segments_overlap?(_, []), do: false

  defp segments_overlap?([left | left_rest], [right | right_rest]) do
    (left == right or String.starts_with?(left, ":") or String.starts_with?(right, ":")) and
      segments_overlap?(left_rest, right_rest)
  end
end
